GROUP_REPOS = [
        {
            "name": "DenDanskeMetode",
            "gitLinks": ["https://github.com/DenDanskeMetode/legacyProject"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": [],
            "documentation": [],
            "members": ["Felix Llambias", "Nicholas Ladik", "Christian Skovgaard", "Victor Lotz"],
        },
                {
            "name": "TheRizzlers",
            "gitLinks": ["https://github.com/TheRizzlersOrg4Semester/Rizzlerpies.git"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": ["Node", "Express", "SSR (EJS)"],
            "documentation": ["https://github.com/TheRizzlersOrg4Semester/Rizzlerpies/blob/main/README.md"],
            "members": ["Mike", "Johan", "Esben", "Mathias"],
        },
                {
            "name": "LNS",
            "gitLinks": ["https://github.com/Linus-nisse-segmentering/Agile-Linus"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": ["ruby","sinatra","rack/rackup", "puma", "ERB", "SQlite3", "HTML", "CSS"],
            "documentation": [],
            "members": ["Lukas", "Nixhajete", "Sahra"],
        },
        
                {
            "name": "Ostemadprissse",
            "gitLinks": ["https://github.com/ostemadprinsesse/Dinner-served-and-ate"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": ["JavaScript, React, Node.js"],
            "documentation": [],
            "members": ["Linea", "Jonas", "Føen (Faprao)", "Nikoleta"],
        },
  {
            "name": "BalladeBaderne",
            "gitLinks": ["https://github.com/Balladebaderne/cookbook"],
            "backend": "SQL",
            "frontend": "React",
            "monitoring": "",
            "stack": ["Node.js","React"],
            "documentation": ["https://github.com/Balladebaderne/cookbook/blob/master/README.md"],
            "members": ["Magnus Giemsa", "Laurits Munk", "Elias Garcia", "Andreas Brandenborg", "Jacob Bisgård"],
        }
]
